# Files to compile that don't have a main() function
CXXFILES = 

# Files to compile that do have a main() function
TARGETS = bench

# Pull in the common makefile stuff
include ../common/makefile.common
