# Files to compile that don't have a main() function
CXXFILES = 

# Files to compile that do have a main() function
# TARGETS = bench_canary bench
TARGETS = bench

# Pull in the common makefile stuff
include include-cache/common/makefile.common
