# Let the programmer choose 32 or 64 bits, but default to 32
BITS ?= 64

# Directory names
ODIR := ./obj$(BITS)
output_folder := $(shell mkdir -p $(ODIR))

# Names of files that the compiler generates
EXEFILES  = $(patsubst %, $(ODIR)/%,   $(TARGETS))
OFILES    = $(patsubst %, $(ODIR)/%.o, $(CXXFILES))
OFILESC   = $(patsubst %, $(ODIR)/%.o, $(CFILES))
EXEOFILES = $(patsubst %, $(ODIR)/%.o, $(TARGETS))
DEPS      = $(patsubst %, $(ODIR)/%.d, $(CXXFILES) $(CFILES) $(TARGETS))

# Compiler and compiler-specific flags (CSFLAGS)
GPP = g++
CXX = $(GPP)
#CXX = clang++

ifeq ($(CXX),$(GPP))
  CSFLAGS = #-fgnu-tm
else
  CSFLAGS =
endif

NOWARNFLAGS = -Wno-class-memaccess

# NB: use += so that we can add additional flags in the files that include this

# General flags
CXXFLAGS += -mrtm -MMD -m$(BITS) -std=c++20 -Wall -Wextra $(CSFLAGS) $(NOWARNFLAGS) 
LDFLAGS += -m$(BITS) -pthread -lpthread $(CSFLAGS)

# Flags for performance
#CXXFLAGS += -O3 -DNDEBUG 

# Flags for debug
#CXXFLAGS += -Og -ggdb 

# Flags for profiling
CXXFLAGS += -Og -ggdb -DNDEBUG

# Build 'all' by default, and don't clobber intermediate files
.DEFAULT_GOAL = all
.PRECIOUS: $(OFILES) $(EXEOFILES)
.PHONY: all clean

# Goal is to build all executables
all: $(EXEFILES)

# Rules for building C++ object files
$(ODIR)/%.o: %.cc
	@echo "[CXX] $< --> $@"
	@$(CXX) $< -o $@ -c $(CXXFLAGS)

# Rules for building executables... we assume an executable uses *all* of the 
# OFILES
$(ODIR)/%: $(ODIR)/%.o $(OFILES)
	@echo "[LD] $< --> $@"
	@$(CXX) $^ -o $@ $(LDFLAGS)

# clean by clobbering the build folder
clean:
	@echo Cleaning up...
	@rm -rf $(ODIR) $(DEPLOY) $(TURNIN)

# Include any dependencies we generated previously
-include $(DEPS)
